copy /b SHFT_DICT_DSC.sql+SHFT_DICT.sql+SHFT_GROUP.sql+SHFT_RULE.sql+SHFT_OPERATOR_RESTRGRP.sql tables.sql
copy /b tables.sql+SHFT_SHIFT_PROC.sql+SHFT_SHIFT_TYPE.sql+SHFT_OPERATOR.sql+SHFT_OPERATOR_EXC.sql+SHFT_SHIFT.sql+SHFT_SHIFT_OPERATOR.sql tables.sql
copy /b tables.sql+SHFT_SHIFT_FAILEDRULELOG.sql+SHFT_SHIFT_ASSGNLOG.sql+SHFT_SHIFT_REASSGNLOG.sql tables.sql
