-----------------------------------------------
-- Procedure Operator table
-----------------------------------------------

create sequence SHFT_OPERATOR_SQ_ID minvalue 1 start with 1 increment by 1;


create table SHFT_OPERATOR
(
  ID                  NUMBER,
  PROC_ID             NUMBER,
  OPERATOR_USER_ID    NUMBER,
  OPERATOR_USERNAME   VARCHAR2(128),
  OPERATOR_PERSONNAME VARCHAR2(128),
  STATUS              NUMBER,
  GNR_RUN_COUNTER     NUMBER,
  GNR_STATUS          NUMBER,
  USER_ID             NUMBER,
  USERNAME            VARCHAR2(128),
  PERSONNAME          VARCHAR2(128),
  DSC                 VARCHAR2(4000),
  FD                  DATE,
  TD                  DATE,
  DUMPSEQ             NUMBER,
  ORD_NUM             NUMBER, 
  OPERATOR_PERSONALID VARCHAR2(64),
  RESTRICT_GRP        NUMBER,
  GROUP_ID            NUMBER,
  CONSTRAINT SHFT_OPERATOR_pk_ID_FD PRIMARY KEY (ID, FD), 
  CONSTRAINT SHFT_OPERATOR_fk_GRPID FOREIGN KEY(GROUP_ID) REFERENCES SHFT_GROUP(ID)
);
comment on table SHFT_OPERATOR is 'for each Shift Generation Procedure - list of Operators, participated in it.

Supports Versioning';
comment on column SHFT_OPERATOR.ID is 'Unique ID, generated by sequence +SHFT_OPERATOR_SQ_ID+';
comment on column SHFT_OPERATOR.PROC_ID is 'System ID of the Shift Generation Procedure with which it is done - refers +SHFT_SHIFT_PROC.ID+';
comment on column SHFT_OPERATOR.OPERATOR_USER_ID is 'User ID of the Operator involved in Shift generation';
comment on column SHFT_OPERATOR.OPERATOR_USERNAME is 'UserName of the Operator involved in Shift generation';
comment on column SHFT_OPERATOR.OPERATOR_PERSONNAME is 'PersonName of the Operator involved in Shift generation';
comment on column SHFT_OPERATOR.STATUS is 'Status of the Operator. Possible values are:

1 == Assigned to Shift Generation

2 == SUSPENDED, i.e. temporarily does not participate in SHIFT

10 == Canceled from Shift generation

See Dictionary #14';
comment on column SHFT_OPERATOR.USER_ID is 'User ID - who is responsible for this Step';
comment on column SHFT_OPERATOR.USERNAME is 'User Name - who is responsible for this Step';
comment on column SHFT_OPERATOR.PERSONNAME is 'Person Name - who is responsible for this Step';
comment on column SHFT_OPERATOR.DSC is 'Arbitrary Comment';
comment on column SHFT_OPERATOR.FD is 'Validity period start';
comment on column SHFT_OPERATOR.TD is 'Validity period end';
comment on column SHFT_OPERATOR.ORD_NUM is 'Used during generation of the Procedure - to ensure randomization of Operators: for each new Procedure - Operators participated in it are randomly ordered, which sequential order number is put to this column.
  
This way - we may be sure that treatment of Operators through different procedure is managed in JUST manner and can sequentially 1-by-1 treat Operators by any algorithm in order of increasing of this ORD_NUM value.';
comment on column SHFT_OPERATOR.OPERATOR_PERSONALID is 'Personal number (11-digit) of the Operator which is main identifier of the Operator';
comment on column SHFT_OPERATOR.RESTRICT_GRP is 'Restrict Group (Dictionary #24) this Operator belongs to';
comment on column SHFT_OPERATOR.GROUP_ID is 'System ID of the Group this Operator belongs to. Is reference to the SHFT_GROUP.ID';

-- Indices
create index SHFT_OPERATOR_IPROC on SHFT_OPERATOR (PROC_ID);
create index SHFT_OPERATOR_IUID on SHFT_OPERATOR (OPERATOR_USER_ID);
create index SHFT_OPERATOR_GRID on SHFT_OPERATOR (GROUP_ID);


