-----------------------------------------------
-- Operator Exclusion table
-----------------------------------------------

create sequence SHFT_OPERATOR_EXC_SQ_ID minvalue 1 start with 1 increment by 1;

create table SHFT_OPERATOR_EXC
(
  ID              NUMBER,
  PROC_ID         NUMBER,
  OPERATOR_ID     NUMBER,
  EXC_TYPE        NUMBER,
  EXC_SHIFT_TYPE  NUMBER,
  EXC_SHIFT       NUMBER,
  EXC_PERIOD_FROM DATE,
  EXC_PERIOD_TO   DATE,
  EXC_REASON_TEXT VARCHAR2(1000),
  STATUS          NUMBER,
  USER_ID         NUMBER,
  USERNAME        VARCHAR2(128),
  PERSONNAME      VARCHAR2(128),
  DSC             VARCHAR2(4000),
  FD              DATE,
  TD              DATE,
  DUMPSEQ         NUMBER,
  CORRECTION_GAP  NUMBER, 
  CONSTRAINTS SHFT_OPERATOR_EXC_pk_IDFD PRIMARY KEY(ID, FD)
);


comment on table SHFT_OPERATOR_EXC is 'for each Shift Generation Procedure - list of so-called Exceptions which some Operators can have.

E.g. particular Operator can NOT participate in Nigh shift etc...

Supports Versioning';
comment on column SHFT_OPERATOR_EXC.ID is 'Unique ID, generated by sequence +SHFT_OPERATOR_EXC_SQ_ID+';
comment on column SHFT_OPERATOR_EXC.PROC_ID is 'System ID of the Shift Generation Procedure with which it is done - refers +SHFT_SHIFT_PROC.ID+';
comment on column SHFT_OPERATOR_EXC.OPERATOR_ID is 'System ID of the Operator, refers +SHFT_OPERATOR.ID+';
comment on column SHFT_OPERATOR_EXC.EXC_TYPE is 'Exception type applied to this Operator. Following values are possible:

1 = Excluded to be assigned to the ANY Shift of particular Shift Type. For this Exception Shift Type is indicated in the +EXC_SHIFT_TYPE+

2 = Excluded to be assigned to the particular Shift. For this Exception Shift is indicated in the +EXC_SHIFT+

3 = Excluded to be assigned to the any Shift which hits particular Period. For this Exception Period is indicated in the +EXC_PERIOD_FROM+ and +EXC_PERIOD_TO+

See Dictionary #18';
comment on column SHFT_OPERATOR_EXC.EXC_SHIFT_TYPE is 'Shift Type - see +SHFT_SHIFT_TYPE.TYPE+.

Used along with +EXC_TYPE = 1+';
comment on column SHFT_OPERATOR_EXC.EXC_SHIFT is 'System ID of the Shift this Operator is excluded from - refers +SHFT_SHIFT.ID+.

Used along with +EXC_TYPE = 2+';
comment on column SHFT_OPERATOR_EXC.EXC_PERIOD_FROM is 'Start of the Period Operator is excluded from, that is - Operator will be excluded from ANY Shift which is Intersected with this Period. See as well +EXC_PERIOD_TO+

Used along with +EXC_TYPE = 3+';
comment on column SHFT_OPERATOR_EXC.EXC_PERIOD_TO is 'Start of the Period Operator is excluded from, that is - Operator will be excluded from ANY Shift which is Intersected with this Period. See as well +EXC_PERIOD_FROM+

Used along with +EXC_TYPE = 3+';
comment on column SHFT_OPERATOR_EXC.EXC_REASON_TEXT is 'Exception reason - so far - free text';
comment on column SHFT_OPERATOR_EXC.STATUS is 'Status of the Exception. Possible Values are:

1 == Exception is Active (will be applied during shift generation)

10 = Canceled (will NOT be applied during shift generation)

See Dictionary #22';
comment on column SHFT_OPERATOR_EXC.USER_ID is 'User ID - who is responsible for this Step';
comment on column SHFT_OPERATOR_EXC.USERNAME is 'User Name - who is responsible for this Step';
comment on column SHFT_OPERATOR_EXC.PERSONNAME is 'Person Name - who is responsible for this Step';
comment on column SHFT_OPERATOR_EXC.DSC is 'Arbitrary Comment';
comment on column SHFT_OPERATOR_EXC.FD is 'Validity period start';
comment on column SHFT_OPERATOR_EXC.TD is 'Validity period end';

-- Indices
create index SHFT_OPERATOR_EXC_I_OPID on SHFT_OPERATOR_EXC (OPERATOR_ID);
create index SHFT_OPERATOR_EXC_I_PROPID on SHFT_OPERATOR_EXC (PROC_ID, OPERATOR_ID);


