-----------------------------------------------
-- Shift Type table
-----------------------------------------------

create sequence SHFT_SHIFT_TYPE_SQ_ID minvalue 1 start with 1 increment by 1;


create table SHFT_SHIFT_TYPE
(
  ID                  NUMBER,
  SHIFT_TYPE          NUMBER,
  HOUR_START          NUMBER,
  HOURS               NUMBER,
  CAPACITY            NUMBER,
  STATUS              NUMBER,
  USER_ID             NUMBER,
  USERNAME            VARCHAR2(128),
  PERSONNAME          VARCHAR2(128),
  DSC                 VARCHAR2(4000),
  FD                  DATE,
  TD                  DATE,
  PROC_ID             NUMBER,
  IF_LET_OVERCAPACITY NUMBER,
  OVERCAPACITY_LIMIT  NUMBER,
  CONSTRAINT SHFT_SHIFT_TYPE_pk_IDFD PRIMARY KEY(ID, FD) 
);

comment on table SHFT_SHIFT_TYPE is 'Describes different Shift types

Supports Versioning';
comment on column SHFT_SHIFT_TYPE.ID is 'Unique ID, generated by sequence +SHFT_SHIFT_TYPE_SQ_ID+';
comment on column SHFT_SHIFT_TYPE.SHIFT_TYPE is 'Type of the Shift Type. So far - exists following Types:

1 = 8 hour morning shift

2 = 8 hour day shift

3 = 6 hour evening shift

4 = 7 hour night shift

Note, there may be several Shifts of each Type!

See Dictionary #26';
comment on column SHFT_SHIFT_TYPE.HOUR_START is 'Shift Type start Hour';
comment on column SHFT_SHIFT_TYPE.HOURS is 'Number of Hours in the Shift';
comment on column SHFT_SHIFT_TYPE.CAPACITY is 'Shift Type Capacity, i.e. number of Operators should be assigned to the Shift';
comment on column SHFT_SHIFT_TYPE.STATUS is 'Status of the Shift Type. Possible values are:

1 = Active (used with Generations

10 = Canceled (not used with Generations

See Dictionary #30';

-- Indices
create index SHFT_SHIFT_TYPE_I_PROCID on SHFT_SHIFT_TYPE (PROC_ID);


